# -*- coding: utf-8 -*-
"""Projet Actuariat 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dz_qC_H8zztYToygqRIhsAM22NrvsmJC
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
import math
import numpy as np
import pandas as pnd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, BernoulliNB, CategoricalNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from google.colab import files
import io
uploaded = files.upload()

df = pnd.read_csv("travel insurance.csv", delimiter=",")

display(df.head())

def clean_data(df):
    """
    Nettoie et prépare les données
    """
    # Conversion des types de données
    df['Net_Sales'] = pd.to_numeric(df['Net_Sales'], errors='coerce')
    df['Commision_in_value'] = pd.to_numeric(df['Commision_in_value'], errors='coerce')
    df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
    df['Duration'] = pd.to_numeric(df['Duration'], errors='coerce')
    return df

# Renommage des colonnes pour uniformité
df.columns = [col.strip().replace(' ', '_').replace('(', '').replace(')', '') for col in df.columns]

# Nettoyage des données
df = clean_data(df)

for col in ['Agency', 'Agency_Type', 'Distribution_Channel',
                'Product_Name', 'Destination', 'Gender']:
        if col in df.columns:
            df[col] = df[col].astype(str).str.strip()

# Création de variables dérivées
df['Has_Claim'] = df['Claim'].apply(lambda x: 1 if str(x).strip().lower() == 'yes' else 0)
df['Claim_Amount'] = np.where(df['Has_Claim'] == 1, df['Net_Sales'] * 0.5, 0)

df['Age_Group'] = pd.cut(df['Age'],
                             bins=[0, 25, 40, 60, 100],
                             labels=['18-25', '26-40', '41-60', '61+'],
                             right=False)

# Catégories de durée
df['Duration_Group'] = pd.cut(df['Duration'],
                              bins=[0, 7, 14, 30, 365],
                              labels=['<1 semaine', '1-2 semaines', '2-4 semaines', '>1 mois'])

def get_region(destination):
        asia = ['MALAYSIA', 'SINGAPORE', 'THAILAND', 'INDONESIA', 'VIET NAM',
                'CHINA', 'JAPAN', 'KOREA', 'PHILIPPINES', 'HONG KONG', 'TAIWAN',
                'INDIA', 'MYANMAR']
        europe = ['ITALY', 'DENMARK', 'NORWAY', 'UNITED KINGDOM', 'FRANCE']
        americas = ['UNITED STATES', 'CANADA']
        oceania = ['AUSTRALIA']

        if any(country in str(destination).upper() for country in asia):
            return 'Asie'
        elif any(country in str(destination).upper() for country in europe):
            return 'Europe'
        elif any(country in str(destination).upper() for country in americas):
            return 'Amériques'
        elif any(country in str(destination).upper() for country in oceania):
            return 'Océanie'
        else:
            return 'Autre'

df['Region'] = df['Destination'].apply(get_region)

def exploratory_analysis(df):
    """
    Analyse exploratoire complète
    """
    print("="*80)
    print("ANALYSE EXPLORATOIRE DES DONNÉES")
    print("="*80)

    # Aperçu des données
    print("\n1. APERÇU DES DONNÉES")
    print(f"Nombre total d'enregistrements: {len(df)}")
    print(f"Nombre de variables: {len(df.columns)}")
    print("\nStructure des données:")
    print(df.info())

    # Statistiques descriptives
    print("\n2. STATISTIQUES DESCRIPTIVES")
    print(df.describe())

    # Distribution des variables catégorielles
    print("\n3. DISTRIBUTION DES VARIABLES CATÉGORIELLES")
    categorical_cols = ['Agency', 'Agency_Type', 'Distribution_Channel',
                       'Product_Name', 'Destination', 'Gender', 'Claim']

    for col in categorical_cols:
        if col in df.columns:
            print(f"\n{col}:")
            print(df[col].value_counts())
            print(f"Valeurs manquantes: {df[col].isnull().sum()}")

    # Vérification des valeurs négatives dans les ventes
    print(f"\n4. VENTES NÉGATIVES: {len(df[df['Net_Sales'] < 0])} enregistrements")

    return df

def claim_analysis(df):
    """
    Analyse détaillée de la sinistralité
    """
    print("="*80)
    print("ANALYSE DE LA SINISTRALITÉ")
    print("="*80)

    # Métriques globales
    total_policies = len(df)
    total_claims = df['Has_Claim'].sum()
    claim_frequency = (total_claims / total_policies) * 100

    print(f"\n1. MÉTRIQUES GLOBALES")
    print(f"Nombre total de polices: {total_policies}")
    print(f"Nombre total de sinistres: {total_claims}")
    print(f"Taux de sinistralité global: {claim_frequency:.2f}%")

    # Sinistralité par segment
    print("\n2. SINISTRALITÉ PAR SEGMENT")

    # Par Groupe d'Âge
    print("\nPar Groupe d'Âge:")
    age_analysis = df.groupby('Age_Group').agg(
        Policies=('Has_Claim', 'count'),
        Claims=('Has_Claim', 'sum'),
        Claim_Rate=('Has_Claim', lambda x: x.mean() * 100),
        Avg_Sales=('Net_Sales', 'mean')
    ).round(2)
    print(age_analysis)

    # Par Genre
    print("\nPar Genre:")
    gender_analysis = df.groupby('Gender').agg(
        Policies=('Has_Claim', 'count'),
        Claims=('Has_Claim', 'sum'),
        Claim_Rate=('Has_Claim', lambda x: x.mean() * 100)
    ).round(2)
    print(gender_analysis)

    # Par Destination/Région
    print("\nPar Région:")
    region_analysis = df.groupby('Region').agg(
        Policies=('Has_Claim', 'count'),
        Claims=('Has_Claim', 'sum'),
        Claim_Rate=('Has_Claim', lambda x: x.mean() * 100),
        Avg_Duration=('Duration', 'mean')
    ).round(2)
    print(region_analysis)

    # Par Durée
    print("\nPar Groupe de Durée:")
    duration_analysis = df.groupby('Duration_Group').agg(
        Policies=('Has_Claim', 'count'),
        Claims=('Has_Claim', 'sum'),
        Claim_Rate=('Has_Claim', lambda x: x.mean() * 100)
    ).round(2)
    print(duration_analysis)

    # Par Produit
    print("\nPar Produit:")
    product_analysis = df.groupby('Product_Name').agg(
        Policies=('Has_Claim', 'count'),
        Claims=('Has_Claim', 'sum'),
        Claim_Rate=('Has_Claim', lambda x: x.mean() * 100),
        Avg_Sales=('Net_Sales', 'mean'),
        Avg_Commission=('Commision_in_value', 'mean')
    ).round(2)
    print(product_analysis.sort_values('Claim_Rate', ascending=False))

    # Par Canal de Distribution
    print("\nPar Canal de Distribution:")
    channel_analysis = df.groupby('Distribution_Channel').agg(
        Policies=('Has_Claim', 'count'),
        Claims=('Has_Claim', 'sum'),
        Claim_Rate=('Has_Claim', lambda x: x.mean() * 100),
        Total_Sales=('Net_Sales', 'sum'),
        Total_Commission=('Commision_in_value', 'sum')
    ).round(2)
    print(channel_analysis)

    # Par Type d'Agence
    print("\nPar Type d'Agence:")
    agency_type_analysis = df.groupby('Agency_Type').agg(
        Policies=('Has_Claim', 'count'),
        Claims=('Has_Claim', 'sum'),
        Claim_Rate=('Has_Claim', lambda x: x.mean() * 100)
    ).round(2)
    print(agency_type_analysis)

    return {
        'age_analysis': age_analysis,
        'gender_analysis': gender_analysis,
        'region_analysis': region_analysis,
        'product_analysis': product_analysis,
        'channel_analysis': channel_analysis
    }

def profitability_analysis(df):
    """
    Analyse de la rentabilité par segment
    """
    print("="*80)
    print("ANALYSE DE RENTABILITÉ")
    print("="*80)

    # Création d'une mesure de rentabilité simplifiée
    # Hypothèse: Coût des sinistres = 50% des ventes nettes pour les polices avec sinistre
    df['Estimated_Claim_Cost'] = df['Net_Sales'] * df['Has_Claim'] * 0.5
    df['Profit'] = df['Net_Sales'] - df['Estimated_Claim_Cost'] - df['Commision_in_value']

    # Rentabilité par produit
    print("\n1. RENTABILITÉ PAR PRODUIT")
    profit_by_product = df.groupby('Product_Name').agg(
        Policies=('Has_Claim', 'count'),
        Total_Sales=('Net_Sales', 'sum'),
        Total_Commission=('Commision_in_value', 'sum'),
        Estimated_Claims=('Estimated_Claim_Cost', 'sum'),
        Total_Profit=('Profit', 'sum')
    ).round(2)

    profit_by_product['Profit_Margin'] = (profit_by_product['Total_Profit'] /
                                         profit_by_product['Total_Sales'] * 100)
    print(profit_by_product.sort_values('Profit_Margin', ascending=False))

    # Rentabilité par canal
    print("\n2. RENTABILITÉ PAR CANAL")
    profit_by_channel = df.groupby('Distribution_Channel').agg(
        Policies=('Has_Claim', 'count'),
        Total_Sales=('Net_Sales', 'sum'),
        Total_Commission=('Commision_in_value', 'sum'),
        Estimated_Claims=('Estimated_Claim_Cost', 'sum'),
        Total_Profit=('Profit', 'sum')
    ).round(2)

    profit_by_channel['Commission_Rate'] = (profit_by_channel['Total_Commission'] /
                                           profit_by_channel['Total_Sales'] * 100)
    profit_by_channel['Claim_Rate'] = (profit_by_channel['Estimated_Claims'] /
                                      profit_by_channel['Total_Sales'] * 100)
    print(profit_by_channel)

    # Top 5 des destinations les plus rentables
    print("\n3. TOP 5 DESTINATIONS PAR RENTABILITÉ")
    profit_by_destination = df.groupby('Destination').agg(
        Policies=('Has_Claim', 'count'),
        Total_Sales=('Net_Sales', 'sum'),
        Total_Profit=('Profit', 'sum'),
        Claim_Rate=('Has_Claim', 'mean')
    ).round(2)

    profit_by_destination['Profit_Margin'] = (profit_by_destination['Total_Profit'] /
                                             profit_by_destination['Total_Sales'] * 100)
    print(profit_by_destination.sort_values('Profit_Margin', ascending=False).head(5))

    return profit_by_product, profit_by_channel

def create_visualizations(df, analyses):
    """
    Crée des visualisations pour l'analyse
    """
    print("\n" + "="*80)
    print("CRÉATION DES VISUALISATIONS")
    print("="*80)

    # Configuration des graphiques
    fig, axes = plt.subplots(3, 2, figsize=(15, 15))
    plt.subplots_adjust(hspace=0.3, wspace=0.3)

    # 1. Distribution des âges
    axes[0, 0].hist(df['Age'].dropna(), bins=20, edgecolor='black', alpha=0.7)
    axes[0, 0].set_title('Distribution de l\'Âge des Assurés')
    axes[0, 0].set_xlabel('Âge')
    axes[0, 0].set_ylabel('Fréquence')
    axes[0, 0].axvline(df['Age'].mean(), color='red', linestyle='--',
                      label=f'Moyenne: {df["Age"].mean():.1f}')
    axes[0, 0].legend()

    # 2. Taux de sinistralité par groupe d'âge
    age_data = analyses['age_analysis']
    axes[0, 1].bar(age_data.index.astype(str), age_data['Claim_Rate'])
    axes[0, 1].set_title('Taux de Sinistralité par Groupe d\'Âge')
    axes[0, 1].set_xlabel('Groupe d\'Âge')
    axes[0, 1].set_ylabel('Taux de Sinistralité (%)')
    axes[0, 1].tick_params(axis='x', rotation=45)

    # Ajout des valeurs sur les barres
    for i, v in enumerate(age_data['Claim_Rate']):
        axes[0, 1].text(i, v + 0.5, f'{v:.1f}%', ha='center')

    # 3. Taux de sinistralité par région
    region_data = analyses['region_analysis']
    axes[1, 0].bar(region_data.index, region_data['Claim_Rate'])
    axes[1, 0].set_title('Taux de Sinistralité par Région')
    axes[1, 0].set_xlabel('Région')
    axes[1, 0].set_ylabel('Taux de Sinistralité (%)')
    axes[1, 0].tick_params(axis='x', rotation=45)

    # 4. Distribution des durées de voyage
    axes[1, 1].hist(df['Duration'].dropna(), bins=20, edgecolor='black', alpha=0.7)
    axes[1, 1].set_title('Distribution de la Durée des Voyages')
    axes[1, 1].set_xlabel('Durée (jours)')
    axes[1, 1].set_ylabel('Fréquence')
    axes[1, 1].axvline(df['Duration'].mean(), color='red', linestyle='--',
                      label=f'Moyenne: {df["Duration"].mean():.1f} jours')
    axes[1, 1].legend()

    # 5. Taux de sinistralité par produit (top 10)
    product_data = analyses['product_analysis'].sort_values('Claim_Rate', ascending=False).head(10)
    axes[2, 0].barh(range(len(product_data)), product_data['Claim_Rate'])
    axes[2, 0].set_yticks(range(len(product_data)))
    axes[2, 0].set_yticklabels(product_data.index, fontsize=9)
    axes[2, 0].set_title('Top 10 Produits par Taux de Sinistralité')
    axes[2, 0].set_xlabel('Taux de Sinistralité (%)')

    # 6. Heatmap: Âge vs Durée pour les sinistres
    if len(df[df['Has_Claim'] == 1]) > 0:
        claim_data = df[df['Has_Claim'] == 1]
        axes[2, 1].scatter(claim_data['Age'], claim_data['Duration'],
                          alpha=0.6, c='red', edgecolors='black')
        axes[2, 1].set_title('Sinistres: Âge vs Durée du Voyage')
        axes[2, 1].set_xlabel('Âge')
        axes[2, 1].set_ylabel('Durée (jours)')
        axes[2, 1].grid(True, alpha=0.3)

    plt.suptitle('Analyse Actuarielle - Assurance Voyage', fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.savefig('analyse_actuarielle.png', dpi=300, bbox_inches='tight')
    plt.show()

    # Graphique supplémentaire: Performance des canaux
    fig2, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

    channel_data = analyses['channel_analysis']
    x = range(len(channel_data))

    # Graphique à barres groupées
    width = 0.35
    ax1.bar(x, channel_data['Policies'], width, label='Polices', alpha=0.8)
    ax1.bar([i + width for i in x], channel_data['Claims'], width, label='Sinistres', alpha=0.8)
    ax1.set_xlabel('Canal de Distribution')
    ax1.set_ylabel('Nombre')
    ax1.set_title('Polices vs Sinistres par Canal')
    ax1.set_xticks([i + width/2 for i in x])
    ax1.set_xticklabels(channel_data.index, rotation=45)
    ax1.legend()

    # Graphique de taux de sinistralité
    ax2.bar(channel_data.index, channel_data['Claim_Rate'])
    ax2.set_xlabel('Canal de Distribution')
    ax2.set_ylabel('Taux de Sinistralité (%)')
    ax2.set_title('Taux de Sinistralité par Canal')
    ax2.tick_params(axis='x', rotation=45)

    plt.tight_layout()
    plt.savefig('performance_canaux.png', dpi=300, bbox_inches='tight')
    plt.show()

def statistical_tests(df):
    """
    Effectue des tests statistiques sur les données
    """
    print("="*80)
    print("TESTS STATISTIQUES")
    print("="*80)

    # Test de différence de sinistralité entre genres
    print("\n1. TEST DE DIFFÉRENCE ENTRE GENRES")
    male_claims = df[df['Gender'] == 'M']['Has_Claim']
    female_claims = df[df['Gender'] == 'F']['Has_Claim']

    if len(male_claims) > 0 and len(female_claims) > 0:
        t_stat, p_value = stats.ttest_ind(male_claims, female_claims, nan_policy='omit')
        print(f"Test t indépendant entre hommes et femmes:")
        print(f"t-statistique: {t_stat:.3f}")
        print(f"p-value: {p_value:.4f}")

        if p_value < 0.05:
            print("Conclusion: Différence significative au seuil de 5%")
        else:
            print("Conclusion: Pas de différence significative")
    else:
        print("Données insuffisantes pour le test par genre")

    # Corrélation entre âge et sinistralité
    print("\n2. CORRÉLATION ÂGE - SINISTRALITÉ")
    correlation = df['Age'].corr(df['Has_Claim'])
    print(f"Coefficient de corrélation: {correlation:.3f}")

    # ANOVA entre groupes d'âge
    print("\n3. ANOVA ENTRE GROUPES D'ÂGE")
    age_groups = []
    for group in df['Age_Group'].cat.categories:
        group_data = df[df['Age_Group'] == group]['Has_Claim']
        if len(group_data) > 0:
            age_groups.append(group_data)

    if len(age_groups) >= 2:
        f_stat, p_value = stats.f_oneway(*age_groups)
        print(f"F-statistique: {f_stat:.3f}")
        print(f"p-value: {p_value:.4f}")

        if p_value < 0.05:
            print("Conclusion: Au moins un groupe d'âge diffère significativement")
        else:
            print("Conclusion: Pas de différence significative entre groupes d'âge")

def generate_report(df, analyses, profit_by_product, profit_by_channel):
    """
    Génère un rapport synthèse de l'analyse
    """
    print("="*80)
    print("RAPPORT SYNTHÈSE - ANALYSE ACTUARIELLE")
    print("="*80)

    # Calcul des métriques clés
    total_policies = len(df)
    total_claims = df['Has_Claim'].sum()
    claim_rate = (total_claims / total_policies) * 100
    total_sales = df['Net_Sales'].sum()
    avg_premium = df['Net_Sales'].mean()

    # Top 3 produits à risque
    top_risk_products = analyses['product_analysis'].sort_values('Claim_Rate', ascending=False).head(3)

    # Top 3 destinations à risque
    region_risk = analyses['region_analysis'].sort_values('Claim_Rate', ascending=False).head(3)

    print(f"\nMÉTRIQUES CLÉS:")
    print(f"- Nombre total de polices: {total_policies}")
    print(f"- Taux de sinistralité global: {claim_rate:.2f}%")
    print(f"- Chiffre d'affaires total: ${total_sales:,.2f}")
    print(f"- Prime moyenne: ${avg_premium:.2f}")

    print(f"\nPRODUITS À HAUT RISQUE (Top 3):")
    for product, row in top_risk_products.iterrows():
        print(f"  - {product}: {row['Claim_Rate']:.1f}% de sinistralité")

    print(f"\nRÉGIONS À HAUT RISQUE (Top 3):")
    for region, row in region_risk.iterrows():
        print(f"  - {region}: {row['Claim_Rate']:.1f}% de sinistralité")

    print(f"\nCANAL LE PLUS RENTABLE:")
    most_profitable_channel = profit_by_channel.loc[profit_by_channel['Total_Profit'].idxmax()]
    print(f"  - {profit_by_channel['Total_Profit'].idxmax()}:")
    print(f"    Profit: ${most_profitable_channel['Total_Profit']:,.2f}")
    print(f"    Marge: {most_profitable_channel['Total_Profit']/most_profitable_channel['Total_Sales']*100:.1f}%")

    print(f"\nRECOMMANDATIONS STRATÉGIQUES:")
    print("1. Révision des tarifs pour les produits et régions à haut risque")
    print("2. Optimisation des commissions pour les canaux peu rentables")
    print("3. Développement ciblé sur les segments à faible sinistralité")
    print("4. Renforcement des contrôles pour les voyages de longue durée")
    print("5. Étude approfondie des destinations à risque élevé")

"""### Exécution de l'Analyse Exploratoire des Données"""

df = exploratory_analysis(df)

"""####  l'Analyse Exploratoire:
Volume et Structure des Données: Nous disposons d'un volume substantiel de 63 326 polices, ce qui est généralement suffisant pour des analyses statistiques robustes. La présence de 16 variables offre une bonne base pour l'identification de facteurs de risque. La création de Age_Group et Duration_Group est une excellente initiative pour la segmentation des risques.
Qualité des Données: C'est un point critique pour tout actuaire.
Valeurs Manquantes: Les null dans Age_Group et Duration_Group (environ 1.5% et 2% respectivement) doivent être investigués. Des valeurs manquantes non aléatoires pourraient biaiser l'analyse de ces segments. Plus préoccupant est le grand nombre de valeurs 'nan' dans la colonne Gender (environ 71%). Leur faible taux de sinistralité (0.64%) par rapport aux genres identifiés (F: 3.90%, M: 3.13%) suggère qu'il ne s'agit pas d'un risque moyen. Ceci pourrait indiquer une catégorie de clients distincte, ou un problème de collecte de données pour un segment à faible risque. Un actuaire devrait insister sur l'imputation ou une analyse séparée de ce segment pour éviter une sous-estimation ou sur-estimation des risques des genres identifiés.
Ventes Négatives: Les 678 enregistrements avec Net_Sales négatifs (environ 1.1% du portefeuille) sont des anomalies. Actuariellement, cela pourrait représenter des annulations, des remboursements ou des erreurs de saisie. Il est crucial de comprendre leur nature, car ils impactent directement le chiffre d'affaires, la prime moyenne et la rentabilité. Dans une modélisation, ils devraient être traités (e.g., exclus, ramenés à zéro si ce sont des remboursements).
Durée Négative: Le min de Duration à -2 est également une anomalie qui doit être corrigée, car une durée de voyage ne peut être négative. Cela peut affecter les calculs de durée moyenne et les segmentations par durée.

### Exécution de l'Analyse de la Sinistralité
"""

analyses_results = claim_analysis(df)

"""#### l'Analyse de la Sinistralité:
Taux de Sinistralité Global (TSG): À 1.46%, le TSG est relativement bas. Cela suggère que l'assurance voyage est, en moyenne, une ligne d'affaires à faible fréquence de sinistres. Cependant, ce chiffre global masque des disparités importantes.
Segmentation par Âge: Les 18-25 ans (TSG de 2.65%) et les 61+ ans (TSG de 1.78%) présentent des taux de sinistralité supérieurs à la moyenne. L'approche actuarielle serait de confirmer si ces différences sont statistiquement significatives (l'ANOVA le suggère) et d'envisager des ajustements de prime par tranche d'âge ou des critères de souscription spécifiques pour ces segments, notamment pour les jeunes voyageurs qui peuvent prendre plus de risques.
Segmentation par Genre: Le taux de sinistralité des femmes (3.90%) est significativement plus élevé que celui des hommes (3.13%) parmi les genres identifiés. Ceci est une information clé pour la tarification, bien qu'il faille considérer les réglementations locales concernant l'utilisation du genre comme facteur de tarification. L'impact des 'nan' de genre, avec un TSG très faible (0.64%), doit être isolé pour une analyse précise des genres connus.
Segmentation par Région: L'Asie, avec un TSG de 1.60%, représente le plus grand volume de polices et de sinistres. L'Europe et les Amériques ont des TSG similaires (1.35%-1.44%), tandis que l'Océanie et la catégorie 'Autre' ont des TSG plus faibles. Un actuaire approfondirait l'analyse par pays au sein de l'Asie pour identifier les hotspots de sinistralité (e.g., infrastructures médicales, risques géopolitiques, coût moyen du sinistre).
Segmentation par Durée: Les voyages de plus d'un mois (>1 mois) ont le TSG le plus élevé (1.61%). C'est une tendance logique car une exposition plus longue augmente la probabilité de sinistre. La tarification devrait idéalement être ajustée de manière non linéaire avec la durée.
Segmentation par Produit: Ceci est le point le plus critique. Des produits tels que Annual Silver Plan (11.03%), Annual Gold Plan (10.82%), et Annual Travel Protect Gold (10.00%) affichent des taux de sinistralité extrêmement élevés, bien au-dessus du TSG global. Cela indique un déséquilibre potentiellement grave entre la prime collectée et le risque porté. Ces produits sont des alertes rouges actuarielles et nécessitent une révision immédiate des primes, des conditions de souscription, des franchises ou des garanties couvertes.
Segmentation par Canal et Type d'Agence: Le taux de sinistralité des Airlines (3.39%) est beaucoup plus élevé que celui des Travel Agency (0.73%). Cela peut suggérer des différences fondamentales dans le profil de risque des clients ciblés par ces canaux, la nature des produits vendus, ou la qualité du processus de vente et d'information client. Il est vital de comprendre si les produits vendus par les compagnies aériennes sont intrinsèquement plus risqués ou si la tarification est inadaptée à ce canal.

### Exécution de l'Analyse de Rentabilité
"""

profit_by_product, profit_by_channel = profitability_analysis(df)

"""#### l'Analyse de Rentabilité:
Rentabilité par Produit: La Profit_Margin est la métrique clé ici. Les produits avec des marges proches de 100% (e.g., Child Comprehensive Plan, Cancellation Plan) sont probablement ceux où il n'y a eu aucun sinistre ou très peu, ou les commissions sont nulles. Il faut s'assurer que ces marges sont robustes et non le fruit d'un manque de données. À l'inverse, Rental Vehicle Excess Insurance avec une marge de 23.93% et Travel Cruise Protect Family avec une marge négative indiquent des problèmes de rentabilité. Pour Rental Vehicle Excess Insurance, la faible marge est probablement due à une commission élevée (plus de 277k de commission pour 369k de ventes) qui écrase le profit malgré un TSG modéré. L'actuaire doit évaluer la viabilité de ces produits et proposer des ajustements sur les primes, les commissions ou les garanties.
Rentabilité par Canal: Le canal Online est clairement dominant en termes de ventes et de profit total. Sa marge de 74.2% est excellente. Le canal Offline, malgré une marge absolue de profit plus faible, a un Commission_Rate légèrement supérieur (24.66% vs 24.09%) et une Claim_Rate plus faible (0.99% vs 1.71%). L'optimisation ne réside pas uniquement dans le profit total mais aussi dans l'efficacité du canal. Les actuaires pourraient explorer comment maintenir la Claim_Rate basse de l'Offline tout en améliorant sa Profit_Margin (e.g., renégocier les commissions ou pousser des produits plus rentables via ce canal).
Top 5 Destinations Rentables: La liste des destinations avec 100% de marge est suspicieuse. Cela signifie que pour ces destinations, il n'y a eu aucun sinistre. Actuariellement, il faut vérifier le volume de polices vendues pour ces destinations. Si le volume est très faible, cette marge de 100% n'est pas statistiquement fiable et ne doit pas servir de base pour des décisions stratégiques robustes.

### Création des Visualisations
"""

create_visualizations(df, analyses_results)

"""#### Visualisations:
Les visualisations confirment intuitivement les observations numériques : la distribution d'âge et de durée, la forte variation des TSG par produit (graphique des top 10 produits à risque), et la différence de performance entre canaux. Elles sont un support essentiel pour la communication des résultats aux décideurs non actuariels.

### Exécution des Tests Statistiques
"""

statistical_tests(df)

"""#### Tests Statistiques:
Différence de Genre: Le test t (p-value = 0.0050) confirme une différence significative dans la sinistralité entre les genres. C'est un facteur potentiellement robuste pour la segmentation actuarielle, sous réserve des contraintes réglementaires et éthiques.
Corrélation Âge-Sinistralité: La corrélation faible (-0.012) indique que l'âge pris comme variable continue n'a pas une relation linéaire forte avec la sinistralité. Cependant, l'ANOVA démontre que les groupes d'âge sont significativement différents. Cela renforce l'approche de segmentation par tranches d'âge plutôt que d'utiliser l'âge comme une variable continue dans un modèle linéaire simple.observées sont statistiquement significatives ou dues au hasard. Ces tests fournissent une base solide pour étayer les conclusions des analyses exploratoires.

### Génération du Rapport Synthèse
"""

generate_report(df, analyses_results, profit_by_product, profit_by_channel)

"""#### Interprétation du Rapport Synthèse:
Le rapport final consolide toutes les analyses en présentant les métriques clés, les produits et régions à haut risque, le canal le plus rentable, et des recommandations stratégiques. C'est le résumé exécutif de l'étude, offrant des insights actionnables pour optimiser la gestion des risques, ajuster les stratégies de tarification et de marketing, et améliorer la rentabilité globale de l'assurance voyage.
"""